# Generated by Django 4.2.7 on 2024-02-16 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APPARTMENT', 'КВАРТИРА'), ('PRIVATE HOUSE', 'ЧАСТНЫЙ ДОМ'), ('COMMERCIAL_ESTATE', 'КОММЕРЧЕСКАЯ НЕДВИЖИМОСТЬ')], max_length=100, verbose_name='Недвижимость')),
                ('location', models.CharField(choices=[('BISHKEK', 'Бишкек'), ('BOSTERY', 'Бостери'), ('BALYKCHY', 'Балыкчы'), ('TOKMOK', 'Токмок')], max_length=100, verbose_name='локация')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('price_currency', models.CharField(choices=[('DOLLAR', 'Доллар USA'), ('SOM', 'Сом')], max_length=20, verbose_name='Цена в')),
                ('number_of_rooms', models.CharField(choices=[('2 ROOMS', '2 КОМНАТЫ'), ('3 ROOMS', '3 КОМНАТЫ'), ('7 ROOMS', '7 КОМНАТЫ'), ('6 ROOMS', '6 КОМНАТЫ'), ('4 ROOMS', '4 КОМНАТЫ'), ('5 ROOMS', '5 КОМНАТЫ'), ('1 ROOM', '1 КОМНАТА')], max_length=100, verbose_name='Количество комнат')),
                ('square', models.IntegerField(verbose_name='Площадь(м2)')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Этаж')),
                ('year_of_buildings', models.CharField(choices=[('2020-current', '2020-наст.время'), ('2010-2019', '2010-2019'), ('2000-2009', '2000:2009'), ('1990-1999', '1990-1999'), ('UNTILL 19650', 'До 1950'), ('1960-1969', '1960-1969'), ('1980-1989', '1980-1989'), ('1970-1979', '1970-1979'), ('1950-1959', '1950-1959')], max_length=100, verbose_name='Год постройки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Введите год выпуска автомобиля', validators=[django.core.validators.MinValueValidator(1940)], verbose_name='Год')),
                ('type_of_body', models.CharField(choices=[('SEDAN', 'Седан'), ('UNIVERSAL', 'Универсал'), ('CABRIOLET', 'Кабриолет'), ('HATCHBACK', 'Хетчбек'), ('SUV', 'Внедорожник'), ('CROSSOVER', 'Кроссовер')], max_length=15, verbose_name='Тип кузова')),
                ('transmission', models.CharField(choices=[('AUTOMAT', 'Автомат'), ('MECHANICS', 'Механика')], max_length=15, verbose_name='Коробка передач')),
                ('wheel', models.CharField(choices=[('RIGTH', 'Правый'), ('LEFT', 'Левый')], max_length=10, verbose_name='Руль')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('condition', models.CharField(choices=[('EMERGENCY', 'Не на ходу'), ('GOOD', 'Хорошее'), ('NEW', 'Новое'), ('EXCELLENT', 'Идеальное')], max_length=20, verbose_name='Состояние')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='auto_photos/')),
                ('price_currency', models.CharField(choices=[('DOLLAR', 'Доллар USA'), ('SOM', 'Сом')], max_length=20, verbose_name='Цена в')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('availability', models.CharField(choices=[('TO_ORDER', 'На заказ'), ('IN_STOCK', 'В Наличии'), ('ON_THE_WAY', 'В пути')], max_length=20, verbose_name='Наличие')),
                ('car_exchange', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да')], max_length=20, verbose_name='Возможность обмена')),
                ('location', models.CharField(choices=[('BISHKEK', 'Бишкек'), ('BOSTERY', 'Бостери'), ('BALYKCHY', 'Балыкчы'), ('TOKMOK', 'Токмок')], max_length=100, verbose_name='локация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
    ]
