# Generated by Django 5.0.2 on 2024-02-12 08:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(help_text='Введите год выпуска автомобиля', validators=[django.core.validators.MinValueValidator(1940)], verbose_name='Год')),
                ('type_of_body', models.CharField(choices=[('SEDAN', 'Седан'), ('HATCHBACK', 'Хетчбек'), ('UNIVERSAL', 'Универсал'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Внедорожник'), ('CABRIOLET', 'Кабриолет')], max_length=15, verbose_name='Тип кузова')),
                ('transmission', models.CharField(choices=[('MECHANICS', 'Механика'), ('AUTOMAT', 'Автомат')], max_length=15, verbose_name='Коробка передач')),
                ('wheel', models.CharField(choices=[('LEFT', 'Левый'), ('RIGTH', 'Правый')], max_length=10, verbose_name='Руль')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('condition', models.CharField(choices=[('GOOD', 'Хорошее'), ('EXCELLENT', 'Идеальное'), ('EMERGENCY', 'Не на ходу'), ('NEW', 'Новое')], max_length=20, verbose_name='Состояние')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='auto_photos/')),
                ('price_currency', models.CharField(choices=[('DOLLAR', 'Доллар USA'), ('SOM', 'Сом')], max_length=20, verbose_name='Цена в')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('availability', models.CharField(choices=[('IN_STOCK', 'В Наличии'), ('TO_ORDER', 'На заказ'), ('ON_THE_WAY', 'В пути')], max_length=20, verbose_name='Наличие')),
                ('car_exchange', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20, verbose_name='Возможность обмена')),
                ('location', models.CharField(choices=[('BISHKEK', 'Бишкек'), ('TOKMOK', 'Токмок'), ('BOSTERY', 'Бостери'), ('BALYKCHY', 'Балыкчы')], max_length=100, verbose_name='локация')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APPARTMENT', 'КВАРТИРА'), ('COMMERCIAL_ESTATE', 'КОММЕРЧЕСКАЯ НЕДВИЖИМОСТЬ'), ('PRIVATE HOUSE', 'ЧАСТНЫЙ ДОМ')], max_length=100, verbose_name='Недвижимость')),
                ('location', models.CharField(choices=[('BISHKEK', 'Бишкек'), ('TOKMOK', 'Токмок'), ('BOSTERY', 'Бостери'), ('BALYKCHY', 'Балыкчы')], max_length=100, verbose_name='локация')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('price_currency', models.CharField(choices=[('DOLLAR', 'Доллар USA'), ('SOM', 'Сом')], max_length=20, verbose_name='Цена в')),
                ('number_of_rooms', models.CharField(choices=[('1ROOM', '1КОМНАТА'), ('2ROOM', '2КОМНАТЫ'), ('3ROOM', '3КОМНАТЫ'), ('4ROOM', '4КОМНАТЫ'), ('5ROOM', '5КОМНАТЫ'), ('6ROOM', '6КОМНАТЫ'), ('7ROOM', '7КОМНАТЫ')], max_length=100, verbose_name='Количество комнат')),
                ('square', models.IntegerField(verbose_name='Площадь(м2)')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Этаж')),
                ('year_of_buildings', models.CharField(choices=[('UNTILL 19650', 'До 1950'), ('1950-1959', '1950-1959'), ('1960-1969', '1960-1969'), ('1970-1979', '1970-1979'), ('1980-1989', '1980-1989'), ('1990-1999', '1990-1999'), ('2000-2009', '2000:2009'), ('2010-2019', '2010-2019'), ('2020-current', '2020-наст.время')], max_length=100, verbose_name='Год постройки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category')),
            ],
        ),
    ]
